services:
  - type: web
    name: assistencia-tecnica-backend
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_TYPE
        value: supabase
      - key: SUPABASE_URL
        value: https://siazsdgodjfmpenmukon.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: WHATSAPP_ENABLED
        value: false
      - key: LOG_LEVEL
        value: info
      - key: UPLOAD_MAX_SIZE
        value: 10485760
      - key: CORS_ORIGIN
        value: https://assistencia-tecnica-mu.vercel.app
    autoDeploy: true
    branch: main
    rootDir: backend